name: gh-pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter clean && flutter pub cache repair

      # Building manually while waiting on the merge of
      # https://github.com/bluefireteam/flutter-gh-pages/pull/7

      # - uses: bluefireteam/flutter-gh-pages@v7
      #   with:
      #     baseHref: /elpcd/
      #     webRenderer: canvaskit

      - run: flutter build web --wasm --release --base-href /elpcd/
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh-pages --force
