name: gh-pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter clean && flutter pub cache repair
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /elpcd/
          webRenderer: canvaskit
